In [1]:
!pip install beautifulsoup4
!pip install glob
!pip install pandas

Requirement already satisfied: beautifulsoup4 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (4.14.2)
Requirement already satisfied: soupsieve>1.2 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from beautifulsoup4) (4.14.0)
ERROR: Could not find a version that satisfies the requirement glob (from versions: none)
ERROR: No matching distribution found for glob
Requirement already satisfied: pandas in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
!pip install newspaper3k lxml_html_clean

Requirement already satisfied: newspaper3k in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (0.2.8)
Requirement already satisfied: lxml_html_clean in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (0.4.3)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (4.14.2)
Requirement already satisfied: Pillow>=3.3.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (11.2.1)
Requirement already satisfied: PyYAML>=3.11 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (6.0.2)
Requirement already satisfied: cssselect>=0.9.2 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (1.3.0)
Requirement already satisfied: lxml>=3.6.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (6.0.2)
Requirement already satisfied: nltk>=3.2.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (3.9.2)
Requirement already satisfied: requests>=2.10.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (2.32.3)
Requirement already satisfied: feedparser>=5.2.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (6.0.12)
Requirement already satisfied: tldextract>=2.0.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (5.3.0)
Requirement already satisfied: feedfinder2>=0.0.4 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from newspaper3k) (0.3)
Requirement already satisfied: soupsieve>1.2 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.14.0)
Requirement already satisfied: six in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: sgmllib3k in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: click in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from nltk>=3.2.1->newspaper3k) (8.3.0)
Requirement already satisfied: joblib in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from nltk>=3.2.1->newspaper3k) (1.5.0)
Requirement already satisfied: regex>=2021.8.3 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from nltk>=3.2.1->newspaper3k) (2024.11.6)
Requirement already satisfied: tqdm in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from nltk>=3.2.1->newspaper3k) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from requests>=2.10.0->newspaper3k) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from requests>=2.10.0->newspaper3k) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from requests>=2.10.0->newspaper3k) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from requests>=2.10.0->newspaper3k) (2025.4.26)
Requirement already satisfied: requests-file>=1.4 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from tldextract>=2.0.1->newspaper3k) (3.0.1)
Requirement already satisfied: filelock>=3.0.8 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from tldextract>=2.0.1->newspaper3k) (3.18.0)

In [3]:
import sys
print(sys.executable)

/Users/ryanxavier/miniforge3/envs/rag_poc/bin/python

In [8]:
from bs4 import BeautifulSoup
from newspaper import Article
import glob
import pandas as pd
import requests


key = "ea04f85bdd4b485c9c93f5faca413d05"
url = "https://newsapi.org/v2/everything"  
topic = "Columbus Day"
cond = {"q": topic,"language": "en", "pageSize": 75, "apiKey": key, "sortBy": "relevancy"}

call = requests.get(url, params=cond)
raw_art = call.json()
article_list = []
for a in raw_art.get("articles", []):
    raw_url = a.get("url")

    raw_text = None
    try:
        curr_art = Article(raw_url)
        curr_art.download()
        curr_art.parse()
        raw_text = curr_art.text
        s = BeautifulSoup(curr_art.text, "html.parser")
    except Exception as e:
        raw_text = None
    
    article_list.append({
        "statement": raw_text
    })




df = pd.DataFrame(article_list)
df = df[df['statement'].notna() & (df['statement'].str.strip() != '')]

df

                                            statement
0   President Trump has signed a proclamation decl...
1   President Trump signs proclamation protecting ...
2   This story is based on a conversation with Hea...
3   Editor’s note: This story contains information...
4   by\n\nNOTE: I'm on vacation returning next wee...
..                                                ...
68  Welcome to the start of another “work” week: M...
69  A quartet of fall season arrivals began previe...
70  The final day of the MLS season came and went,...
71  Back in 1492, Christopher Columbus sailed the ...
72  Some traders will get a break on Monday. Just ...

[71 rows x 1 columns]

In [5]:
import sys
print(sys.executable)

/Users/ryanxavier/miniforge3/envs/rag_poc/bin/python

In [10]:
print(df.loc[0, 'statement'])

President Trump has signed a proclamation declaring Monday to be Columbus Day, in an effort to "reclaim" what he called the famed explorer's "extraordinary legacy of faith, courage, perseverance, and virtue."

The proclamation comes after Trump said in a social media post in April that, to

bring the holiday "back from the ashes," he would reinstate "Columbus Day under the same rules, dates, and locations, as it has had for all of the many decades before!"

In recent years, many people have instead celebrated Indigenous Peoples Day to recognize Native land and acknowledge the contributions Native Americans have made to the country.

Critics and advocates like Kerri Malloy, a professor of Native American and Indigenous Studies at San José State University, have challenged Columbus Day and Columbus' legacy. He says Columbus' arrival to the Americas "triggered a mass genocide of Indigenous people throughout the Western hemisphere," which included deadly diseases being spread among them, their land being stolen and being forced into Christianity.

Thursday's proclamation does not mention Indigenous Peoples Day, but it accuses "left-wing arsonists" of trying to "destroy [Columbus'] name and dishonor his memory."

Columbus Day is one of 12 federally recognized holidays in 2025. According to the Pew Research Center, 30 states and three U.S. territories recognize Columbus Day in some way, while 17 states and D.C. commemorate Indigenous people on that day. Included in those tallies are the several states that recognize both. In 2021, Joe Biden became the first president to officially recognize Indigenous Peoples Day on the same date as Columbus Day.

Christopher Columbus was born in Italy in 1451 and sailed to what he thought would be Asia in 1492, with support from the Spanish monarchy. He instead arrived in what is now the Bahamas. He would make three more voyages to South America, Central America and the Caribbean before his death, but never made it to what is now the U.S., according to Britannica.

President Benjamin Harrison first commemorated Columbus Day in 1892, a year after anti-Italian rhetoric culminated in the murder of 11 Italian immigrants in New Orleans by a lynch mob. The attack put a strain on the relationship between Italy and the U.S., and the holiday was an olive branch. President Franklin Roosevelt proclaimed it a federal holiday in 1934.

After signing the document on Thursday, Trump said, "We're back, Italians. We love the Italians."

Rep. Elise Stefanik, a New York Republican, lauded his proclamation, writing on X, "New Yorkers [love] Columbus Day!"

Rep. Mike Lawler, a New York Republican and Italian American, said on X, "Viva Italia! As a proud Italian-American, I fully support protecting Columbus Day and celebrating the rich history and contributions of Italian-Americans."

Others weren't as enthused.

"The proclamation reiterates the American fantasy of Columbus' voyage, as solely a story of discovery and exploration, versus what it really was about — commerce and the exploitation of resources," said Malloy, the San José State professor. "You can't tell a story without telling both sides of it."

Still, the president is encouraging Americans to celebrate Columbus in some way on the holiday, and display the U.S. flag on all public buildings.

"This is the president trolling people of color, underrepresented minorities that tend not to vote for his party or candidacy," said Matthew Fletcher, director of the Indigenous Law and Policy Center at Michigan State University. "My sense is there's not a massive groundswell in favor of Columbus Day anymore, except, possibly, the Italian Americans."

Fletcher said that regardless of what the day is called, Indigenous people will still celebrate and be celebrated.

"It's local, it's tribal, it's statewide in a lot of places, and it's still going to be a legitimate thing, and people take it seriously," he said.

In [6]:
df['statement'] = (
    df['statement']
    .astype(str)  
    .str.replace(r'\s+', ' ', regex=True) 
    .str.strip() 
)

In [7]:
df

Empty DataFrame
Columns: [statement]
Index: []